cmake_minimum_required(VERSION 3.22.0)

project(caiwei-project VERSION 1.0.0 LANGUAGES C CXX)

if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Debug)
endif()

option(ENABLE_CAIWEI_TEST        "Build Test"          OFF)
option(ENABLE_CAIWEI_MNN         "MNN Runtime"         OFF)
option(ENABLE_CAIWEI_CUDA        "CUDA Runtime"        ON)
option(ENABLE_CAIWEI_RKNN        "RKNN Runtime"        OFF)
option(ENABLE_CAIWEI_ASCEND      "Ascend Runtime"      OFF)
option(ENABLE_CAIWEI_OPENVINO    "OpenVINO Runtime"    OFF)
option(ENABLE_CAIWEI_TENSORRT    "TensorRT Runtime"    OFF)
option(ENABLE_CAIWEI_LLAMACPP    "llama.cpp Runtime"   OFF)
option(ENABLE_CAIWEI_ONNXRUNTIME "ONNXRuntime Runtime" ON)

if(ANDROID)
    set(CMAKE_C_STANDARD 17)
    set(CMAKE_C_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_STANDARD 17)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_EXTENSIONS OFF)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -Wextra")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra")
elseif(CMAKE_HOST_UNIX)
    set(CMAKE_C_STANDARD 17)
    set(CMAKE_C_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_STANDARD 17)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_EXTENSIONS OFF)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -Wextra")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra")
    set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK "${CMAKE_COMMAND} -E time")
    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE "${CMAKE_COMMAND} -E time")
elseif(CMAKE_HOST_WIN32)
    if(MSVC)
        set(CMAKE_C_STANDARD 17)
        set(CMAKE_C_STANDARD_REQUIRED ON)
        set(CMAKE_CXX_STANDARD 17)
        set(CMAKE_CXX_STANDARD_REQUIRED ON)
        set(CMAKE_CXX_EXTENSIONS OFF)
        add_compile_options("/utf-8" "/Zc:__cplusplus")
    else()
        message(FATAL_ERROR "需要安装MSVC开发环境")
    endif()
else()
    message(FATAL_ERROR "不支持的系统：${CMAKE_HOST_SYSTEM_NAME}")
endif()