name: build
on:
  push:
    branches: [ master ]
jobs:
  chobits:
    name: Build chobits
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout deps
        run: |
          mkdir deps
          cd    deps
          sudo  apt -y update
          sudo  apt -y install gcc g++ wget cmake unzip libsdl2-dev libcpp-httplib-dev
          sudo  apt -y install ffmpeg libavutil-dev libavcodec-dev libavdevice-dev libavformat-dev libswscale-dev libswresample-dev
          wget  https://github.com/microsoft/onnxruntime/releases/download/v1.28.1/onnxruntime-linux-x64-1.28.1.tgz > /dev/null 2>&1
          tar   -zxvf onnxruntime-linux-x64-1.28.1.tgz > /dev/null 2>&1
          mv    onnxruntime-linux-x64-1.28.1 onnxruntime
          cd    onnxruntime
          ln    -sf lib lib64
          mv    include onnxruntime
          mkdir include
          mv    onnxruntime include
      - name: Deploy chobits
        run: |
          mkdir build
          cd    build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make
          sudo make install
          